export const countries = [
  { value: "af", label: "Afghanistan" },
  { value: "al", label: "Albania" },
  { value: "dz", label: "Algeria" },
  { value: "ad", label: "Andorra" },
  { value: "ao", label: "Angola" },
  { value: "ar", label: "Argentina" },
  { value: "am", label: "Armenia" },
  { value: "au", label: "Australia" },
  { value: "at", label: "Austria" },
  { value: "az", label: "Azerbaijan" },
  { value: "bs", label: "Bahamas" },
  { value: "bh", label: "Bahrain" },
  { value: "bd", label: "Bangladesh" },
  { value: "bb", label: "Barbados" },
  { value: "by", label: "Belarus" },
  { value: "be", label: "Belgium" },
  { value: "bz", label: "Belize" },
  { value: "bj", label: "Benin" },
  { value: "bt", label: "Bhutan" },
  { value: "bo", label: "Bolivia" },
  { value: "ba", label: "Bosnia and Herzegovina" },
  { value: "bw", label: "Botswana" },
  { value: "br", label: "Brazil" },
  { value: "bn", label: "Brunei" },
  { value: "bg", label: "Bulgaria" },
  { value: "bf", label: "Burkina Faso" },
  { value: "bi", label: "Burundi" },
  { value: "kh", label: "Cambodia" },
  { value: "cm", label: "Cameroon" },
  { value: "ca", label: "Canada" },
  { value: "cv", label: "Cape Verde" },
  { value: "cf", label: "Central African Republic" },
  { value: "td", label: "Chad" },
  { value: "cl", label: "Chile" },
  { value: "cn", label: "China" },
  { value: "co", label: "Colombia" },
  { value: "km", label: "Comoros" },
  { value: "cg", label: "Congo" },
  { value: "cd", label: "Congo (Democratic Republic)" },
  { value: "cr", label: "Costa Rica" },
  { value: "ci", label: "Côte d'Ivoire" },
  { value: "hr", label: "Croatia" },
  { value: "cu", label: "Cuba" },
  { value: "cy", label: "Cyprus" },
  { value: "cz", label: "Czech Republic" },
  { value: "dk", label: "Denmark" },
  { value: "dj", label: "Djibouti" },
  { value: "dm", label: "Dominica" },
  { value: "do", label: "Dominican Republic" },
  { value: "ec", label: "Ecuador" },
  { value: "eg", label: "Egypt" },
  { value: "sv", label: "El Salvador" },
  { value: "gq", label: "Equatorial Guinea" },
  { value: "er", label: "Eritrea" },
  { value: "ee", label: "Estonia" },
  { value: "sz", label: "Eswatini" },
  { value: "et", label: "Ethiopia" },
  { value: "fj", label: "Fiji" },
  { value: "fi", label: "Finland" },
  { value: "fr", label: "France" },
  { value: "ga", label: "Gabon" },
  { value: "gm", label: "Gambia" },
  { value: "ge", label: "Georgia" },
  { value: "de", label: "Germany" },
  { value: "gh", label: "Ghana" },
  { value: "gr", label: "Greece" },
  { value: "gd", label: "Grenada" },
  { value: "gt", label: "Guatemala" },
  { value: "gn", label: "Guinea" },
  { value: "gw", label: "Guinea-Bissau" },
  { value: "gy", label: "Guyana" },
  { value: "ht", label: "Haiti" },
  { value: "hn", label: "Honduras" },
  { value: "hu", label: "Hungary" },
  { value: "is", label: "Iceland" },
  { value: "in", label: "India" },
  { value: "id", label: "Indonesia" },
  { value: "ir", label: "Iran" },
  { value: "iq", label: "Iraq" },
  { value: "ie", label: "Ireland" },
  { value: "il", label: "Israel" },
  { value: "it", label: "Italy" },
  { value: "jm", label: "Jamaica" },
  { value: "jp", label: "Japan" },
  { value: "jo", label: "Jordan" },
  { value: "kz", label: "Kazakhstan" },
  { value: "ke", label: "Kenya" },
  { value: "ki", label: "Kiribati" },
  { value: "kp", label: "Korea (North)" },
  { value: "kr", label: "Korea (South)" },
  { value: "kw", label: "Kuwait" },
  { value: "kg", label: "Kyrgyzstan" },
  { value: "la", label: "Laos" },
  { value: "lv", label: "Latvia" },
  { value: "lb", label: "Lebanon" },
  { value: "ls", label: "Lesotho" },
  { value: "lr", label: "Liberia" },
  { value: "ly", label: "Libya" },
  { value: "li", label: "Liechtenstein" },
  { value: "lt", label: "Lithuania" },
  { value: "lu", label: "Luxembourg" },
  { value: "mg", label: "Madagascar" },
  { value: "mw", label: "Malawi" },
  { value: "my", label: "Malaysia" },
  { value: "mv", label: "Maldives" },
  { value: "ml", label: "Mali" },
  { value: "mt", label: "Malta" },
  { value: "mh", label: "Marshall Islands" },
  { value: "mr", label: "Mauritania" },
  { value: "mu", label: "Mauritius" },
  { value: "mx", label: "Mexico" },
  { value: "fm", label: "Micronesia" },
  { value: "md", label: "Moldova" },
  { value: "mc", label: "Monaco" },
  { value: "mn", label: "Mongolia" },
  { value: "me", label: "Montenegro" },
  { value: "ma", label: "Morocco" },
  { value: "mz", label: "Mozambique" },
  { value: "mm", label: "Myanmar" },
  { value: "na", label: "Namibia" },
  { value: "nr", label: "Nauru" },
  { value: "np", label: "Nepal" },
  { value: "nl", label: "Netherlands" },
  { value: "nz", label: "New Zealand" },
  { value: "ni", label: "Nicaragua" },
  { value: "ne", label: "Niger" },
  { value: "ng", label: "Nigeria" },
  { value: "mk", label: "North Macedonia" },
  { value: "no", label: "Norway" },
  { value: "om", label: "Oman" },
  { value: "pk", label: "Pakistan" },
  { value: "pw", label: "Palau" },
  { value: "ps", label: "Palestine" },
  { value: "pa", label: "Panama" },
  { value: "pg", label: "Papua New Guinea" },
  { value: "py", label: "Paraguay" },
  { value: "pe", label: "Peru" },
  { value: "ph", label: "Philippines" },
  { value: "pl", label: "Poland" },
  { value: "pt", label: "Portugal" },
  { value: "qa", label: "Qatar" },
  { value: "ro", label: "Romania" },
  { value: "ru", label: "Russia" },
  { value: "rw", label: "Rwanda" },
  { value: "kn", label: "Saint Kitts and Nevis" },
  { value: "lc", label: "Saint Lucia" },
  { value: "vc", label: "Saint Vincent and the Grenadines" },
  { value: "ws", label: "Samoa" },
  { value: "sm", label: "San Marino" },
  { value: "st", label: "São Tomé and Príncipe" },
  { value: "sa", label: "Saudi Arabia" },
  { value: "sn", label: "Senegal" },
  { value: "rs", label: "Serbia" },
  { value: "sc", label: "Seychelles" },
  { value: "sl", label: "Sierra Leone" },
  { value: "sg", label: "Singapore" },
  { value: "sk", label: "Slovakia" },
  { value: "si", label: "Slovenia" },
  { value: "sb", label: "Solomon Islands" },
  { value: "so", label: "Somalia" },
  { value: "za", label: "South Africa" },
  { value: "ss", label: "South Sudan" },
  { value: "es", label: "Spain" },
  { value: "lk", label: "Sri Lanka" },
  { value: "sd", label: "Sudan" },
  { value: "sr", label: "Suriname" },
  { value: "se", label: "Sweden" },
  { value: "ch", label: "Switzerland" },
  { value: "sy", label: "Syria" },
  { value: "tw", label: "Taiwan" },
  { value: "tj", label: "Tajikistan" },
  { value: "tz", label: "Tanzania" },
  { value: "th", label: "Thailand" },
  { value: "tl", label: "Timor-Leste" },
  { value: "tg", label: "Togo" },
  { value: "to", label: "Tonga" },
  { value: "tt", label: "Trinidad and Tobago" },
  { value: "tn", label: "Tunisia" },
  { value: "tr", label: "Turkey" },
  { value: "tm", label: "Turkmenistan" },
  { value: "tv", label: "Tuvalu" },
  { value: "ug", label: "Uganda" },
  { value: "ua", label: "Ukraine" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "gb", label: "United Kingdom" },
  { value: "us", label: "United States" },
  { value: "uy", label: "Uruguay" },
  { value: "uz", label: "Uzbekistan" },
  { value: "vu", label: "Vanuatu" },
  { value: "va", label: "Vatican City" },
  { value: "ve", label: "Venezuela" },
  { value: "vn", label: "Vietnam" },
  { value: "ye", label: "Yemen" },
  { value: "zm", label: "Zambia" },
  { value: "zw", label: "Zimbabwe" },
];

export const countryCodes = [
  { value: "in", label: "India (+91)", code: "+91" },
  { value: "us", label: "United States (+1)", code: "+1" },
  { value: "gb", label: "United Kingdom (+44)", code: "+44" },
  { value: "ca", label: "Canada (+1)", code: "+1" },
  { value: "au", label: "Australia (+61)", code: "+61" },
  { value: "de", label: "Germany (+49)", code: "+49" },
  { value: "fr", label: "France (+33)", code: "+33" },
  { value: "it", label: "Italy (+39)", code: "+39" },
  { value: "es", label: "Spain (+34)", code: "+34" },
  { value: "nl", label: "Netherlands (+31)", code: "+31" },
  { value: "jp", label: "Japan (+81)", code: "+81" },
  { value: "kr", label: "Korea (South) (+82)", code: "+82" },
  { value: "cn", label: "China (+86)", code: "+86" },
  { value: "br", label: "Brazil (+55)", code: "+55" },
  { value: "ru", label: "Russia (+7)", code: "+7" },
  { value: "pk", label: "Pakistan (+92)", code: "+92" },
  { value: "bd", label: "Bangladesh (+880)", code: "+880" },
  { value: "ng", label: "Nigeria (+234)", code: "+234" },
  { value: "mx", label: "Mexico (+52)", code: "+52" },
  { value: "af", label: "Afghanistan (+93)", code: "+93" },
  { value: "al", label: "Albania (+355)", code: "+355" },
  { value: "dz", label: "Algeria (+213)", code: "+213" },
  { value: "ad", label: "Andorra (+376)", code: "+376" },
  { value: "ao", label: "Angola (+244)", code: "+244" },
  { value: "ar", label: "Argentina (+54)", code: "+54" },
  { value: "am", label: "Armenia (+374)", code: "+374" },
  { value: "at", label: "Austria (+43)", code: "+43" },
  { value: "az", label: "Azerbaijan (+994)", code: "+994" },
  { value: "bs", label: "Bahamas (+1-242)", code: "+1-242" },
  { value: "bh", label: "Bahrain (+973)", code: "+973" },
  { value: "bb", label: "Barbados (+1-246)", code: "+1-246" },
  { value: "by", label: "Belarus (+375)", code: "+375" },
  { value: "be", label: "Belgium (+32)", code: "+32" },
  { value: "bz", label: "Belize (+501)", code: "+501" },
  { value: "bj", label: "Benin (+229)", code: "+229" },
  { value: "bt", label: "Bhutan (+975)", code: "+975" },
  { value: "bo", label: "Bolivia (+591)", code: "+591" },
  { value: "ba", label: "Bosnia and Herzegovina (+387)", code: "+387" },
  { value: "bw", label: "Botswana (+267)", code: "+267" },
  { value: "bn", label: "Brunei (+673)", code: "+673" },
  { value: "bg", label: "Bulgaria (+359)", code: "+359" },
  { value: "bf", label: "Burkina Faso (+226)", code: "+226" },
  { value: "bi", label: "Burundi (+257)", code: "+257" },
  { value: "kh", label: "Cambodia (+855)", code: "+855" },
  { value: "cm", label: "Cameroon (+237)", code: "+237" },
  { value: "cv", label: "Cape Verde (+238)", code: "+238" },
  { value: "cf", label: "Central African Republic (+236)", code: "+236" },
  { value: "td", label: "Chad (+235)", code: "+235" },
  { value: "cl", label: "Chile (+56)", code: "+56" },
  { value: "co", label: "Colombia (+57)", code: "+57" },
  { value: "km", label: "Comoros (+269)", code: "+269" },
  { value: "cg", label: "Congo (+242)", code: "+242" },
  { value: "cd", label: "Congo (Democratic Republic) (+243)", code: "+243" },
  { value: "cr", label: "Costa Rica (+506)", code: "+506" },
  { value: "ci", label: "Côte d'Ivoire (+225)", code: "+225" },
  { value: "hr", label: "Croatia (+385)", code: "+385" },
  { value: "cu", label: "Cuba (+53)", code: "+53" },
  { value: "cy", label: "Cyprus (+357)", code: "+357" },
  { value: "cz", label: "Czech Republic (+420)", code: "+420" },
  { value: "dk", label: "Denmark (+45)", code: "+45" },
  { value: "dj", label: "Djibouti (+253)", code: "+253" },
  { value: "dm", label: "Dominica (+1-767)", code: "+1-767" },
  { value: "do", label: "Dominican Republic (+1-809)", code: "+1-809" },
  { value: "ec", label: "Ecuador (+593)", code: "+593" },
  { value: "eg", label: "Egypt (+20)", code: "+20" },
  { value: "sv", label: "El Salvador (+503)", code: "+503" },
  { value: "gq", label: "Equatorial Guinea (+240)", code: "+240" },
  { value: "er", label: "Eritrea (+291)", code: "+291" },
  { value: "ee", label: "Estonia (+372)", code: "+372" },
  { value: "sz", label: "Eswatini (+268)", code: "+268" },
  { value: "et", label: "Ethiopia (+251)", code: "+251" },
  { value: "fj", label: "Fiji (+679)", code: "+679" },
  { value: "fi", label: "Finland (+358)", code: "+358" },
  { value: "ga", label: "Gabon (+241)", code: "+241" },
  { value: "gm", label: "Gambia (+220)", code: "+220" },
  { value: "ge", label: "Georgia (+995)", code: "+995" },
  { value: "gh", label: "Ghana (+233)", code: "+233" },
  { value: "gr", label: "Greece (+30)", code: "+30" },
  { value: "gd", label: "Grenada (+1-473)", code: "+1-473" },
  { value: "gt", label: "Guatemala (+502)", code: "+502" },
  { value: "gn", label: "Guinea (+224)", code: "+224" },
  { value: "gw", label: "Guinea-Bissau (+245)", code: "+245" },
  { value: "gy", label: "Guyana (+592)", code: "+592" },
  { value: "ht", label: "Haiti (+509)", code: "+509" },
  { value: "hn", label: "Honduras (+504)", code: "+504" },
  { value: "hu", label: "Hungary (+36)", code: "+36" },
  { value: "is", label: "Iceland (+354)", code: "+354" },
  { value: "id", label: "Indonesia (+62)", code: "+62" },
  { value: "ir", label: "Iran (+98)", code: "+98" },
  { value: "iq", label: "Iraq (+964)", code: "+964" },
  { value: "ie", label: "Ireland (+353)", code: "+353" },
  { value: "il", label: "Israel (+972)", code: "+972" },
  { value: "jm", label: "Jamaica (+1-876)", code: "+1-876" },
  { value: "jo", label: "Jordan (+962)", code: "+962" },
  { value: "kz", label: "Kazakhstan (+7)", code: "+7" },
  { value: "ke", label: "Kenya (+254)", code: "+254" },
  { value: "ki", label: "Kiribati (+686)", code: "+686" },
  { value: "kp", label: "Korea (North) (+850)", code: "+850" },
  { value: "kw", label: "Kuwait (+965)", code: "+965" },
  { value: "kg", label: "Kyrgyzstan (+996)", code: "+996" },
  { value: "la", label: "Laos (+856)", code: "+856" },
  { value: "lv", label: "Latvia (+371)", code: "+371" },
  { value: "lb", label: "Lebanon (+961)", code: "+961" },
  { value: "ls", label: "Lesotho (+266)", code: "+266" },
  { value: "lr", label: "Liberia (+231)", code: "+231" },
  { value: "ly", label: "Libya (+218)", code: "+218" },
  { value: "li", label: "Liechtenstein (+423)", code: "+423" },
  { value: "lt", label: "Lithuania (+370)", code: "+370" },
  { value: "lu", label: "Luxembourg (+352)", code: "+352" },
  { value: "mg", label: "Madagascar (+261)", code: "+261" },
  { value: "mw", label: "Malawi (+265)", code: "+265" },
  { value: "my", label: "Malaysia (+60)", code: "+60" },
  { value: "mv", label: "Maldives (+960)", code: "+960" },
  { value: "ml", label: "Mali (+223)", code: "+223" },
  { value: "mt", label: "Malta (+356)", code: "+356" },
  { value: "mh", label: "Marshall Islands (+692)", code: "+692" },
  { value: "mr", label: "Mauritania (+222)", code: "+222" },
  { value: "mu", label: "Mauritius (+230)", code: "+230" },
  { value: "fm", label: "Micronesia (+691)", code: "+691" },
  { value: "md", label: "Moldova (+373)", code: "+373" },
  { value: "mc", label: "Monaco (+377)", code: "+377" },
  { value: "mn", label: "Mongolia (+976)", code: "+976" },
  { value: "me", label: "Montenegro (+382)", code: "+382" },
  { value: "ma", label: "Morocco (+212)", code: "+212" },
  { value: "mz", label: "Mozambique (+258)", code: "+258" },
  { value: "mm", label: "Myanmar (+95)", code: "+95" },
  { value: "na", label: "Namibia (+264)", code: "+264" },
  { value: "nr", label: "Nauru (+674)", code: "+674" },
  { value: "np", label: "Nepal (+977)", code: "+977" },
  { value: "nz", label: "New Zealand (+64)", code: "+64" },
  { value: "ni", label: "Nicaragua (+505)", code: "+505" },
  { value: "ne", label: "Niger (+227)", code: "+227" },
  { value: "mk", label: "North Macedonia (+389)", code: "+389" },
  { value: "no", label: "Norway (+47)", code: "+47" },
  { value: "om", label: "Oman (+968)", code: "+968" },
  { value: "pw", label: "Palau (+680)", code: "+680" },
  { value: "ps", label: "Palestine (+970)", code: "+970" },
  { value: "pa", label: "Panama (+507)", code: "+507" },
  { value: "pg", label: "Papua New Guinea (+675)", code: "+675" },
  { value: "py", label: "Paraguay (+595)", code: "+595" },
  { value: "pe", label: "Peru (+51)", code: "+51" },
  { value: "ph", label: "Philippines (+63)", code: "+63" },
  { value: "pl", label: "Poland (+48)", code: "+48" },
  { value: "pt", label: "Portugal (+351)", code: "+351" },
  { value: "qa", label: "Qatar (+974)", code: "+974" },
  { value: "ro", label: "Romania (+40)", code: "+40" },
  { value: "rw", label: "Rwanda (+250)", code: "+250" },
  { value: "kn", label: "Saint Kitts and Nevis (+1-869)", code: "+1-869" },
  { value: "lc", label: "Saint Lucia (+1-758)", code: "+1-758" },
  {
    value: "vc",
    label: "Saint Vincent and the Grenadines (+1-784)",
    code: "+1-784",
  },
  { value: "ws", label: "Samoa (+685)", code: "+685" },
  { value: "sm", label: "San Marino (+378)", code: "+378" },
  { value: "st", label: "São Tomé and Príncipe (+239)", code: "+239" },
  { value: "sa", label: "Saudi Arabia (+966)", code: "+966" },
  { value: "sn", label: "Senegal (+221)", code: "+221" },
  { value: "rs", label: "Serbia (+381)", code: "+381" },
  { value: "sc", label: "Seychelles (+248)", code: "+248" },
  { value: "sl", label: "Sierra Leone (+232)", code: "+232" },
  { value: "sg", label: "Singapore (+65)", code: "+65" },
  { value: "sk", label: "Slovakia (+421)", code: "+421" },
  { value: "si", label: "Slovenia (+386)", code: "+386" },
  { value: "sb", label: "Solomon Islands (+677)", code: "+677" },
  { value: "so", label: "Somalia (+252)", code: "+252" },
  { value: "za", label: "South Africa (+27)", code: "+27" },
  { value: "ss", label: "South Sudan (+211)", code: "+211" },
  { value: "lk", label: "Sri Lanka (+94)", code: "+94" },
  { value: "sd", label: "Sudan (+249)", code: "+249" },
  { value: "sr", label: "Suriname (+597)", code: "+597" },
  { value: "se", label: "Sweden (+46)", code: "+46" },
  { value: "ch", label: "Switzerland (+41)", code: "+41" },
  { value: "sy", label: "Syria (+963)", code: "+963" },
  { value: "tw", label: "Taiwan (+886)", code: "+886" },
  { value: "tj", label: "Tajikistan (+992)", code: "+992" },
  { value: "tz", label: "Tanzania (+255)", code: "+255" },
  { value: "th", label: "Thailand (+66)", code: "+66" },
  { value: "tl", label: "Timor-Leste (+670)", code: "+670" },
  { value: "tg", label: "Togo (+228)", code: "+228" },
  { value: "to", label: "Tonga (+676)", code: "+676" },
  { value: "tt", label: "Trinidad and Tobago (+1-868)", code: "+1-868" },
  { value: "tn", label: "Tunisia (+216)", code: "+216" },
  { value: "tr", label: "Turkey (+90)", code: "+90" },
  { value: "tm", label: "Turkmenistan (+993)", code: "+993" },
  { value: "tv", label: "Tuvalu (+688)", code: "+688" },
  { value: "ug", label: "Uganda (+256)", code: "+256" },
  { value: "ua", label: "Ukraine (+380)", code: "+380" },
  { value: "ae", label: "United Arab Emirates (+971)", code: "+971" },
  { value: "uy", label: "Uruguay (+598)", code: "+598" },
  { value: "uz", label: "Uzbekistan (+998)", code: "+998" },
  { value: "vu", label: "Vanuatu (+678)", code: "+678" },
  { value: "va", label: "Vatican City (+379)", code: "+379" },
  { value: "ve", label: "Venezuela (+58)", code: "+58" },
  { value: "vn", label: "Vietnam (+84)", code: "+84" },
  { value: "ye", label: "Yemen (+967)", code: "+967" },
  { value: "zm", label: "Zambia (+260)", code: "+260" },
  { value: "zw", label: "Zimbabwe (+263)", code: "+263" },
];
